projeto/core/urls.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.conf.urls import url

from .views import HomeView

urlpatterns = [
   url(r'^$', HomeView.as_view(), name='home'),
]

projeto/projeto/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include('core.urls')),
    url(r'usuario/', include('usuario.urls')),
    url(r'categoria/', include('categoria.urls')),
    url(r'instituicao/', include('instituicao.urls')),
    url(r'injuria/', include('injuria.urls')),
    url(r'midia/', include('midia.urls')),
    url(r'pergunta/', include('pergunta.urls')),
    url(r'^accounts/', include('django.contrib.auth.urls')),
]

#url para arquivos de media quando em desenvolvimento
if settings.DEBUG:
    urlpatterns += staticfiles_urlpatterns()
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

projeto/core/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

# Create your models here.

projeto/midia/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.conf import settings
from django.db import models
from django.db.models import signals
from django.dispatch import receiver
from django.utils.translation import ugettext_lazy as _
from django.core.urlresolvers import reverse
# from django.http import HttpResponseRedirect
from django.shortcuts import render
# from .forms import UploadFileForm
# from .models import ModelWithFileField


class Midia(models.Model):
    #1 campo da tupla fica no banco de dados
    #2 campo da tupla eh mostrado para o usuario
    TIPOS = (
        ('TEXTO', 'Texto'),
        ('IMAGEM', 'Imagem'),
        (u'ÁUDIO', u'Áudio')
    )
    legenda = models.CharField('Legenda', max_length=250)
    tipo = models.CharField(_(u'Tipo de mídia'), max_length=7, choices=TIPOS, default='TEXTO')
    arquivo = models.FileField(_(u'Arquivo anexo'), upload_to='uploads/midias',null=True, blank=True)
    
    class Meta:
        ordering = ['tipo']

    def __unicode__(self):
        return '%s - %s ' % (self.tipo, self.legenda)

    def save(self, *args, **kwargs):
        self.tipo = self.tipo.upper()
        super(Midia, self).save(*args, **kwargs)

    @property
    def get_absolute_url(self):
        return reverse('midia_update', args=[str(self.id)])

    @property
    def get_delete_url(self):
        return reverse('midia_delete', args=[str(self.id)])

    @property
    def get_arquivo_url(self):
        return '%s%s' % (settings.MEDIA_URL, self.arquivo)

#deleta os arquivo fisico ao excluir o item midia
@receiver(models.signals.post_delete, sender=Midia)
def auto_delete_file_on_delete(sender, instance, **kwargs):
    if instance.arquivo:
        if os.path.isfile(instance.arquivo.path):
            os.remove(instance.arquivo.path)

#deleta o arquivo fisico ao alterar o arquivo do item midia
@receiver(models.signals.pre_save, sender=Midia)
def auto_delete_file_on_change(sender, instance, **kwargs):
    if not instance.pk:
        return False
    try:
        obj = Midia.objects.get(pk=instance.pk)

        if not obj.arquivo:
            return False

        old_file = obj.arquivo
    except Midia.DoesNotExist:
        return False

    new_file = instance.arquivo
    if not old_file == new_file:
        if os.path.isfile(old_file.path):
            os.remove(old_file.path)

projeto/pergunta/models.py
# coding: utf-8
from __future__ import unicode_literals
from django.db import models
from django.utils.translation import ugettext_lazy as _
from django.core.urlresolvers import reverse

class Pergunta(models.Model):
    numero = models.IntegerField(_(u'Número da pergunta'), null=True, blank=True)
    descricao = models.TextField(_(u'Descrição da pergunta')) 
    numero_exibicoes = models.IntegerField(_(u'Quantidade de vezes que a pergunta foi realizada'), null=True, blank=True)
    injuria = models.ForeignKey('injuria.Injuria', null=True, blank=True)
    midia_texto = models.ForeignKey('midia.Midia', null=True, blank=True)

    class Meta:
        ordering = [u'descricao']

    def __unicode__(self):
        return self.descricao   #'%d - %s ' % (self.numero, self.descricao)

    def save(self, *args, **kwargs):
        self.descricao = self.descricao.upper()
        super(Pergunta, self).save(*args, **kwargs)

    @property
    def get_absolute_url(self):
        return reverse('pergunta_update', args=[str(self.id)])

    @property
    def get_delete_url(self):
        return reverse('pergunta_delete', args=[str(self.id)])

projeto/usuario/models.py
# coding: utf-8
from __future__ import unicode_literals
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager, UserManager
from django.utils.translation import ugettext_lazy as _
from django.core.urlresolvers import reverse

class Usuario(AbstractBaseUser):
    #1 campo da tupla fica no banco de dados
    #2 campo da tupla eh mostrado para o usuario
    TIPOS = (
        ('ADMINISTRADOR', 'Administrador'),
        ('COMUM', 'Comum' )
    )

    USERNAME_FIELD = 'email'

    tipo = models.CharField(_(u'Tipo do usuário'), max_length=15, choices=TIPOS, default='COMUM')
    nome = models.CharField(_(u'Nome'), max_length=100)
    email = models.EmailField(_('Email'), unique=True, max_length=100, db_index=True)
    instituicao = models.ForeignKey('instituicao.Instituicao', null=True, blank=True)
    is_active = models.BooleanField(_(u'ativo'), default=False, help_text='Se ativo o usuário tem permissão para acessar o sistema')

    objects = UserManager()

    class Meta:
        ordering            =   [u'nome']
        verbose_name        =   _(u'usuário')
        verbose_name_plural =   _(u'usuários')

    def __unicode__(self):
        return self.nome

    def has_module_perms(self, app_label):
        return True

    def has_perm(self, perm, obj=None):
        return True

    def get_short_name(self):
        return self.nome[0:10].strip()

    def get_full_name(self):
        return self.nome

    def save(self, *args, **kwargs):
        if not self.id:
            self.set_password(self.password)
        super(Usuario, self).save(*args, **kwargs)

    @property
    def is_staff(self):
        if self.tipo == 'ADMINISTRADOR':
            return True
        return False

    @property
    def get_absolute_url(self):
        return reverse('usuario_update', args=[str(self.id)])

    @property
    def get_delete_url(self):
        return reverse('usuario_delete', args=[str(self.id)])

projeto/core/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.shortcuts import render
from django.views.generic.base import TemplateView

from utils.decorators import LoginRequiredMixin

# Create your views here.
class HomeView(LoginRequiredMixin, TemplateView):
	template_name = 'core/home.html'

projeto/injuria/views.py
# coding: utf-8
from __future__ import unicode_literals
from django.shortcuts import render
from django.views.generic import ListView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from utils.decorators import LoginRequiredMixin
from .models import Injuria

class InjuriaListView(LoginRequiredMixin, ListView):
	model = Injuria

class InjuriaCreateView(LoginRequiredMixin, CreateView):
	model = Injuria
	fields = ['nome', 'descricao', 'midia_texto' ,'instituicao']
	success_url = 'injuria_list'

class InjuriaUpdateView(LoginRequiredMixin, UpdateView):
	model = Injuria
	fields = ['nome', 'descricao', 'midia_texto', 'instituicao']
	success_url = 'injuria_list'

class InjuriaDeleteView(LoginRequiredMixin, DeleteView):
	model = Injuria
	success_url = 'injuria_list'

projeto/core/templates/core/includes/_barra_status.html
{% load bootstrap3 %}
{% block navbar_bottom %}
<footer>
  <nav class="navbar navbar-default navbar-fixed-bottom">
    <div class="container">
      <div class="navbar-header">
        <br>
        <span class="label label-info">{% bootstrap_icon 'user' %}</span>
        <span class="label label-default">{{ user.get_short_name|upper }}</span>
        <span class="label label-info">{% bootstrap_icon 'credit-card' %}</span>
        <span class="label label-default">{{ user.get_tipo_display }}</span>
        <span class="label label-info">{% bootstrap_icon 'bookmark' %}</span>
        <span class="label label-default">Projeto Enfermagem</span>
      </div>
    </div>
  </nav>
</footer>
{% endblock %}

projeto/core/templates/core/includes/_menu_principal.html
{% load bootstrap3 %}
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="{% url 'home' %}">{% bootstrap_icon 'plus' %}</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class=""><a href="{% url 'home' %}"> {% bootstrap_icon 'home' %} Home <span class="sr-only">(current)</span></a></li>
        <li><a href="{% url 'usuario_list' %}">{% bootstrap_icon 'user' %} Usuários</a></li>
        <li><a href="{% url 'instituicao_list' %}">{% bootstrap_icon 'tower' %} Instituições</a></li>
        <li><a href="{% url 'injuria_list' %}">{% bootstrap_icon 'thumbs-down' %} Injúrias</a></li>
        <li><a href="{% url 'midia_list' %}">{% bootstrap_icon 'play' %} Mídias</a></li>        
        <li><a href="{% url 'pergunta_list' %}">{% bootstrap_icon 'question-sign' %} Perguntas</a></li>
        <li><a href="#">{% bootstrap_icon 'ok-sign' %} Respostas</a></li>
        <li><a href="#">{% bootstrap_icon 'play-circle' %} Ações</a></li>
        
        <!-- <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">Separated link</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">One more separated link</a></li>
          </ul>
        </li> -->
      </ul>
      
      <ul class="nav navbar-nav navbar-right">
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Login <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="#">Alterar senha</a></li>
            <li><a href="{% url 'logout' %}?next=/">Sair</a></li>
          </ul>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>